import repos from Archlinux
date: 20240511

diff --git a/gnome-shell/PKGBUILD b/gnome-shell/PKGBUILD
--- a/gnome-shell/PKGBUILD
+++ b/gnome-shell/PKGBUILD
@@ -1,45 +1,73 @@
-# Maintainer: Fabian Bornschein <fabiscafe-at-mailbox-dot-org>
 # Maintainer: Jan Alexander Steffens (heftig) <heftig@archlinux.org>
+# Maintainer: Fabian Bornschein <fabiscafe@archlinux.org>
 # Contributor: Ionut Biru <ibiru@archlinux.org>
 # Contributor: Flamelab <panosfilip@gmail.com
 
-pkgname=gnome-shell
-pkgver=45.3
-pkgrel=1
+pkgbase=gnome-shell
+pkgname=(
+  gnome-shell
+  gnome-shell-docs
+)
+pkgver=46.1
+pkgrel=2
 epoch=1
 pkgdesc="Next generation desktop shell"
 url="https://wiki.gnome.org/Projects/GnomeShell"
 arch=(loong64 x86_64)
-license=(GPL)
+license=(GPL-3.0-or-later)
 depends=(
   accountsservice
+  at-spi2-core
+  bash
+  cairo
+  dconf
+  gcc-libs
   gcr-4
+  gdk-pixbuf2
   gjs
+  glib2
+  glibc
   gnome-autoar
+  gnome-desktop-4
   gnome-session
   gnome-settings-daemon
+  graphene
   gsettings-desktop-schemas
   gtk4
+  hicolor-icon-theme
+  json-glib
   libadwaita
   libcanberra-pulse
   libgdm
+  libgirepository
+  libglvnd
   libgweather-4
   libibus
+  libical
+  libnm
   libnma-gtk4
+  libpipewire
+  libpulse
   libsecret
   libsoup3
+  libx11
+  libxfixes
   mutter
+  pango
+  polkit
+  systemd-libs
   unzip
   upower
+  webkitgtk-6.0
 )
 makedepends=(
   asciidoc
   bash-completion
   evolution-data-server
+  gi-docgen
   git
   gnome-control-center
   gobject-introspection
-  gtk-doc
   meson
   sassc
 )
@@ -48,37 +76,24 @@ checkdepends=(
   python-dbusmock
   xorg-server-xvfb
 )
-optdepends=(
-  'evolution-data-server: Evolution calendar integration'
-  'gnome-bluetooth-3.0: Bluetooth support'
-  'gnome-control-center: System settings'
-  'gnome-disk-utility: Mount with keyfiles'
-  'gst-plugin-pipewire: Screen recording'
-  'gst-plugins-good: Screen recording'
-  'power-profiles-daemon: Power profile switching'
-  'python-gobject: gnome-shell-test-tool performance tester'
-  'switcheroo-control: Multi-GPU support'
-)
-groups=(gnome)
-_commit=c76b18a04282e48f6196ad1f9f1ab6f08c492599  # tags/45.3^0
 source=(
-  "git+https://gitlab.gnome.org/GNOME/gnome-shell.git#commit=$_commit"
+  # GNOME Shell tags use SSH signatures which makepkg doesn't understand
+  "git+https://gitlab.gnome.org/GNOME/gnome-shell.git#tag=${pkgver/[a-z]/.&}"
   "git+https://gitlab.gnome.org/GNOME/libgnome-volume-control.git"
 )
-b2sums=('SKIP'
+b2sums=('7aa8e21a0135a1c5536d19877747a86b1cfa1024b6c378db2364033d2a6b3a3e30875a08176423cc41c7c3a87bb76b5b67df5177aa6d209a726f0f3a3c15dd6a'
         'SKIP')
 
-pkgver() {
-  cd $pkgname
-  git describe --tags | sed 's/[^-]*-g/r&/;s/-/+/g'
-}
-
 prepare() {
-  cd $pkgname
+  cd $pkgbase
+
+  # Fix screencast with GLib 2.80.1
+  # https://discourse.gnome.org/t/security-fixes-for-signal-handling-in-gdbus-in-glib/20882
+  git cherry-pick -n 50a011a19dcc6997ea6173c07bb80b2d9888d363
 
   git submodule init
   git submodule set-url subprojects/gvc "$srcdir/libgnome-volume-control"
-  git -c protocol.file.allow=always submodule update
+  git -c protocol.file.allow=always -c protocol.allow=never submodule update
 }
 
 build() {
@@ -89,27 +104,49 @@ build() {
   CFLAGS="${CFLAGS/-O2/-O3} -fno-semantic-interposition"
   LDFLAGS+=" -Wl,-Bsymbolic-functions"
 
-  arch-meson $pkgname build "${meson_options[@]}"
+  arch-meson $pkgbase build "${meson_options[@]}"
   meson compile -C build
 }
 
-_check() (
+check() (
   export XDG_RUNTIME_DIR="$PWD/rdir"
   mkdir -p -m 700 "$XDG_RUNTIME_DIR"
 
   export NO_AT_BRIDGE=1 GTK_A11Y=none
 
-  meson test -C build --print-errorlogs -t 3
+  # Tests FAIL and or TIMEOUT at random
+  # gnome-shell:shell / fittsy; / headlessStart; / basic; / closeWithActiveWindows
+  dbus-run-session -- xvfb-run -s '-nolisten local +iglx -noreset' \
+    meson test -C build --no-rebuild --print-errorlogs -t 2 || :
 )
 
-check() {
-  dbus-run-session xvfb-run -s '-nolisten local +iglx -noreset' \
-    bash -c "$(declare -f _check); _check"
+package_gnome-shell() {
+  depends+=(libmutter-14.so)
+  optdepends=(
+    'evolution-data-server: Evolution calendar integration'
+    'gnome-bluetooth-3.0: Bluetooth support'
+    'gnome-control-center: System settings'
+    'gnome-disk-utility: Mount with keyfiles'
+    'gst-plugin-pipewire: Screen recording'
+    'gst-plugins-good: Screen recording'
+    'power-profiles-daemon: Power profile switching'
+    'python-gobject: gnome-shell-test-tool performance tester'
+    'python-simplejson: gnome-shell-test-tool performance tester'
+    'switcheroo-control: Multi-GPU support'
+  )
+  groups=(gnome)
+
+  meson install -C build --destdir "$pkgdir"
+
+  mkdir -p doc/usr/share
+  mv {"$pkgdir",doc}/usr/share/doc
 }
 
-package() {
-  depends+=(libmutter-13.so)
-  meson install -C build --destdir "$pkgdir"
+package_gnome-shell-docs() {
+  pkgdesc+=" (API documentation)"
+  depends=()
+
+  mv doc/* "$pkgdir"
 }
 
 # vim:set sw=2 sts=-1 et:
diff --git a/mutter/PKGBUILD b/mutter/PKGBUILD
--- a/mutter/PKGBUILD
+++ b/mutter/PKGBUILD
@@ -1,4 +1,5 @@
 # Maintainer: Jan Alexander Steffens (heftig) <heftig@archlinux.org>
+# Maintainer: Fabian Bornschein <fabiscafe@archlinux.org>
 # Contributor: Ionut Biru <ibiru@archlinux.org>
 # Contributor: Michael Kanis <mkanis_at_gmx_dot_de>
 
@@ -7,32 +8,67 @@ pkgname=(
   mutter
   mutter-docs
 )
-pkgver=45.3
+pkgver=46.1
 pkgrel=1
 pkgdesc="Window manager and compositor for GNOME"
 url="https://gitlab.gnome.org/GNOME/mutter"
 arch=(loong64 x86_64)
-license=(GPL)
+license=(GPL-2.0-or-later)
 depends=(
+  at-spi2-core
+  cairo
   colord
   dconf
+  fontconfig
+  fribidi
+  gcc-libs
+  gdk-pixbuf2
+  glib2
+  glibc
   gnome-desktop-4
   gnome-settings-daemon
   graphene
   gsettings-desktop-schemas
+  gtk4
+  harfbuzz
   iio-sensor-proxy
   lcms2
   libcanberra
+  libcolord
   libdisplay-info
+  libdrm
   libei
+  libglvnd
   libgudev
+  libice
   libinput
+  libpipewire
   libsm
   libsysprof-capture
+  libwacom
+  libx11
+  libxau
+  libxcb
+  libxcomposite
+  libxcursor
+  libxdamage
+  libxext
+  libxfixes
+  libxi
+  libxinerama
+  libxkbcommon
   libxkbcommon-x11
   libxkbfile
+  libxrandr
+  libxtst
+  mesa
+  pango
   pipewire
+  pixman
+  python
   startup-notification
+  systemd-libs
+  wayland
   xorg-xwayland
 )
 makedepends=(
@@ -53,16 +89,11 @@ checkdepends=(
   wireplumber
   zenity
 )
-_commit=5012d22cb96ba22c4133e2e488ea1f5241fb50e2  # tags/45.3^0
 source=(
-  "git+https://gitlab.gnome.org/GNOME/mutter.git#commit=$_commit"
+  # Mutter tags use SSH signatures which makepkg doesn't understand
+  "git+https://gitlab.gnome.org/GNOME/mutter.git#tag=$pkgver"
 )
-b2sums=('SKIP')
-
-pkgver() {
-  cd mutter
-  git describe --tags | sed 's/[^-]*-g/r&/;s/-/+/g'
-}
+b2sums=('4acd4a192455890b12b2fc9b6553ed65bd2176307cd6c6683fc2ab476b7fa88f4b5e507a1209b3e900c68d94768f3cf749b4f5d87d25300b33a112182c8a62a7')
 
 prepare() {
   cd mutter
@@ -73,7 +104,7 @@ build() {
     -D docs=true
     -D egl_device=true
     -D installed_tests=false
-    -D libdisplay_info=true
+    -D libdisplay_info=enabled
     -D wayland_eglstream=true
   )
 
@@ -92,9 +123,14 @@ check() (
   export NO_AT_BRIDGE=1 GTK_A11Y=none
   export MUTTER_DEBUG_DUMMY_MODE_SPECS="800x600@10.0"
 
+  # Tests fail:
+  # mutter:cogl+cogl/conform / cogl-test-offscreen-texture-formats-gles2
+  # mutter:core+mutter/stacking / fullscreen-maximize
+  ## https://gitlab.gnome.org/GNOME/mutter/-/issues/3343
   xvfb-run -s '-nolisten local +iglx -noreset' \
     mutter/src/tests/meta-dbus-runner.py --launch=pipewire --launch=wireplumber \
-    meson test -C build --print-errorlogs -t 5 --setup plain
+    meson test -C build --no-suite 'mutter/kvm' --no-rebuild \
+    --print-errorlogs --timeout-multiplier 10 --setup plain ||:
 )
 
 _pick() {
@@ -108,7 +144,7 @@ _pick() {
 }
 
 package_mutter() {
-  provides=(libmutter-13.so)
+  provides=(libmutter-14.so)
 
   meson install -C build --destdir "$pkgdir"
 
diff --git a/python-pytest-raises/PKGBUILD b/python-pytest-raises/PKGBUILD
--- a/python-pytest-raises/PKGBUILD
+++ b/python-pytest-raises/PKGBUILD
@@ -2,19 +2,19 @@
 
 pkgname=python-pytest-raises
 pkgver=0.11
-pkgrel=4
+pkgrel=5
 pkgdesc='An implementation of pytest.raises as a pytest.mark fixture'
 arch=('any')
 license=('MIT')
 url='https://github.com/Lemmons/pytest-raises'
 depends=('python-pytest')
-makedepends=('python-setuptools')
+makedepends=('python-build' 'python-installer' 'python-setuptools' 'python-wheel')
 source=("https://github.com/Lemmons/pytest-raises/archive/$pkgver/$pkgname-$pkgver.tar.gz")
 sha512sums=('d4df7012941bd06d090fc26018a516c10329d96ba80f69ea9794cb17f632240a4747067cc146dd04c9c9a666a1e7be0458ccf1eb7c74b4bf6e2b73daa56f80ec')
 
 build() {
   cd pytest-raises-$pkgver
-  python setup.py build
+  python -m build --wheel --skip-dependency-check --no-isolation
 }
 
 check() {
@@ -22,14 +22,20 @@ check() {
 
   local site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
   cd pytest-raises-$pkgver
-  python setup.py install --root="$PWD/tmp_install" --optimize=1
-  PYTHONPATH="$PWD/tmp_install$site_packages:$PYTHONPATH" pytest
+  python -m installer --destdir="$PWD/tmp_install" dist/*.whl
+  # Appears to be 2 test runs. 1st run has 4 failures, 2nd has 3 failures
+  PYTHONPATH="$PWD/tmp_install$site_packages:$PYTHONPATH" pytest || true
 }
 
 package() {
   cd pytest-raises-$pkgver
-  python setup.py install --root="$pkgdir" --optimize=1
-  install -Dm644 LICENSE -t "$pkgdir"/usr/share/licenses/$pkgname/
+  python -m installer --destdir="$pkgdir" dist/*.whl
+
+  # Symlink license file
+  local site_packages=$(python -c "import site; print(site.getsitepackages()[0])")
+  install -d "$pkgdir"/usr/share/licenses/$pkgname
+  ln -s "$site_packages"/pytest_raises-$pkgver.dist-info/LICENSE \
+    "$pkgdir"/usr/share/licenses/$pkgname/LICENSE
 }
 
 # vim:set ts=2 sw=2 et:
diff --git a/vigra/PKGBUILD b/vigra/PKGBUILD
--- a/vigra/PKGBUILD
+++ b/vigra/PKGBUILD
@@ -3,56 +3,115 @@
 # Contributor: AndyRTR <andyrtr@archlinux.org>
 # Contributor: Lukas Jirkovsky <l.jirkovsky@gmail.com>
 
-pkgname=vigra
+pkgbase=vigra
+pkgname=(vigra python-vigra)
 pkgver=1.11.2
-pkgrel=1
+pkgrel=4
 pkgdesc='Computer vision library'
 arch=(loong64 x86_64)
 url="https://ukoethe.github.io/$pkgname"
 _url="https://github.com/ukoethe/$pkgname"
 license=(MIT)
-depends=(fftw
-         gcc-libs
-         hdf5
-         libpng
-         libtiff
-         openexr
-         sh)
-makedepends=(boost
-             cmake
-             python-numpy)
+makedepends=(
+  boost
+  cmake
+  fftw
+  hdf5
+  imath
+  libjpeg-turbo
+  libpng
+  libtiff
+  openexr
+  python-h5py
+  python-matplotlib
+  python-numpy
+  python-scipy
+  zlib
+)
 checkdepends=(python-nose)
-optdepends=('python: for python bindings'
-            'boost-libs: for python bindings')
 _pkgver="Version-${pkgver//./-}"
 _archive="$pkgname-$_pkgver"
 source=("$_url/archive/$_pkgver/$_archive.tar.gz"
-        vigra-openexr3.patch)
+        vigra-openexr3.patch
+        $pkgname-1.11.2-remove_imp.patch)
 sha256sums=('4841936f5c3c137611ec782e293d961df29d3b5b70ade8cb711374de0f4cb5d3'
-            '2572717e39f916c7c463b8f49306b683c5923906be2721f7da181c58b3a2b34b')
+            '2572717e39f916c7c463b8f49306b683c5923906be2721f7da181c58b3a2b34b'
+            '496da081edcd2bb709c6c9f523b328170e8a5e0f85712d41a7faad61af5ede65')
 
 prepare() {
-	cd "$_archive"
-	patch -p1 -i ../vigra-openexr3.patch
+  cd "$_archive"
+  patch -p1 -i ../vigra-openexr3.patch
+  # remove the use of the imp module: https://github.com/ukoethe/vigra/pull/560
+  patch -p1 -i ../$pkgname-1.11.2-remove_imp.patch
 }
 
 build() {
-	cmake -B build -S "$_archive" \
-		-DCMAKE_INSTALL_PREFIX=/usr \
-		-DPYTHON_EXECUTABLE=/usr/bin/python \
-		-DDOCINSTALL=share/doc \
-		-DWITH_OPENEXR=true \
-		-DWITH_VIGRANUMPY=1
-		#-DBUILD_DOCS=OFF \
-	make -C build
+  cmake -B build -S "$_archive" \
+    -DCMAKE_INSTALL_PREFIX=/usr \
+    -DPYTHON_EXECUTABLE=/usr/bin/python \
+    -DDOCINSTALL=share/doc \
+    -DWITH_OPENEXR=true \
+    -DWITH_VIGRANUMPY=1
+    #-DBUILD_DOCS=OFF \
+  make -C build
 }
 
 check() {
-	# https://github.com/ukoethe/vigra/issues/491
-	make -C build -j1 -k check || echo "Tests failed"
+  # https://github.com/ukoethe/vigra/issues/491
+  make -C build -j1 -k check || echo "Tests failed"
 }
 
-package() {
-	  make -C build DESTDIR="$pkgdir" install
-	  install -Dm0644 -t "$pkgdir/usr/share/licenses/$pkgname/" "${_archive}/LICENSE.txt"
+_pick() {
+  local p="$1" f d; shift
+  for f; do
+    d="$srcdir/$p/${f#$pkgdir/}"
+    mkdir -p "$(dirname "$d")"
+    mv "$f" "$d"
+    rmdir -p --ignore-fail-on-non-empty "$(dirname "$f")"
+  done
+}
+
+package_vigra() {
+  depends=(
+    gcc-libs
+    glibc
+    hdf5
+    imath
+    libjpeg-turbo
+    libpng
+    libtiff
+    openexr
+    zlib
+  )
+  optdepends=(
+    'python: for vigra-config'
+    'python-vigra: for Python bindings'
+  )
+
+  make -C build DESTDIR="$pkgdir" install
+  install -Dm0644 -t "$pkgdir/usr/share/licenses/$pkgname/" "${_archive}/LICENSE.txt"
+
+  cd "$pkgdir"
+  _pick python-$pkgbase usr/lib/python*
+  _pick python-$pkgbase usr/lib/vigranumpy
+}
+
+package_python-vigra() {
+  pkgdesc+=' - Python bindings'
+  depends=(
+    boost-libs
+    fftw
+    gcc-libs
+    glibc
+    hdf5
+    python
+    python-h5py
+    python-matplotlib
+    python-numpy
+    python-scipy
+    vigra
+  )
+
+  mv -v $pkgname/* "$pkgdir"
+  install -Dm0644 -t "$pkgdir/usr/share/licenses/$pkgname/" "$pkgbase-Version-${pkgver//./-}/LICENSE.txt"
 }
